/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar/Avatar.vue')['default']
    ButtonWave: typeof import('./src/components/Button/ButtonWave.vue')['default']
    CallArea: typeof import('./src/components/CallArea/CallArea.vue')['default']
    CallButton: typeof import('./src/components/Button/CallButton.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./src/components/ContextMenu/ContextMenuItem.vue')['default']
    CopyIcon: typeof import('./src/components/icons/CopyIcon.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer/ImageViewer.vue')['default']
    Loading: typeof import('./src/components/loaders/Loading.vue')['default']
    ReplayIcon: typeof import('./src/components/icons/ReplayIcon.vue')['default']
    RevokeMsgIcon: typeof import('./src/components/icons/RevokeMsgIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroller: typeof import('./src/components/Scroller/index.vue')['default']
    Transition: typeof import('./src/components/Transition/Transition.vue')['default']
    Typing: typeof import('./src/components/Typing/index.vue')['default']
    Viewer: typeof import('./src/components/ImageViewer/Viewer.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/VirtualList.vue')['default']
    VirtualListItem: typeof import('./src/components/VirtualList/VirtualListItem.vue')['default']
  }
}
